Repository dnd-side-project/dnd-6th-5-android, pull requests merged in 2022-02, with the labels that each got.

#4 [setting] 라이브러리 설정 및 SUIT 폰트 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/fork/spoonfeed/SpoonFeedApplication.kt
  app/src/main/java/com/fork/spoonfeed/presentation/MainActivity.kt
  app/src/main/res/font-v26/app_font_suit.xml
  app/src/main/res/font/app_font_suit.xml
  app/src/main/res/font/suit_bold.otf
  app/src/main/res/font/suit_extrabold.otf
  app/src/main/res/font/suit_extralight.otf
  app/src/main/res/font/suit_heavy.otf
  app/src/main/res/font/suit_light.otf
  app/src/main/res/font/suit_medium.otf
  app/src/main/res/font/suit_regular.otf
  app/src/main/res/font/suit_semibold.otf
  app/src/main/res/font/suit_thin.otf
  build.gradle
Labels: 🖥feature

#7 [setting] 컬러 추가 및 폰트 스타일 지정
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: 🖥feature

#8 Feature/5 init setting
  app/src/main/java/com/fork/spoonfeed/presentation/MainActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/temp.java
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/view/CommunityFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/home/temp.java
  app/src/main/java/com/fork/spoonfeed/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/temp.java
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policy/temp.java
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policy/view/PolicyFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/util/ViewExt.kt
  app/src/main/res/drawable/ic_check_round.xml
  app/src/main/res/drawable/ic_check_round_filled.xml
  app/src/main/res/drawable/ic_chevron_down.xml
  app/src/main/res/drawable/ic_chevron_left.xml
  app/src/main/res/drawable/ic_chevron_right.xml
  app/src/main/res/drawable/ic_chevron_up.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_close_filled.xml
  app/src/main/res/drawable/ic_comment_filled.xml
  app/src/main/res/drawable/ic_community.xml
  app/src/main/res/drawable/ic_community_filled.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_home_filled.xml
  app/src/main/res/drawable/ic_info.xml
  app/src/main/res/drawable/ic_like.xml
  app/src/main/res/drawable/ic_like_filled.xml
  app/src/main/res/drawable/ic_mypage.xml
  app/src/main/res/drawable/ic_mypage_filled.xml
  app/src/main/res/drawable/ic_policy.xml
  app/src/main/res/drawable/ic_policy_filled.xml
  app/src/main/res/drawable/ic_save.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/drawable/ic_write.xml
  app/src/main/res/drawable/rectangle_top_gray03.xml
  app/src/main/res/drawable/selector_community.xml
  app/src/main/res/drawable/selector_home.xml
  app/src/main/res/drawable/selector_mypage.xml
  app/src/main/res/drawable/selector_policy.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_policy.xml
  app/src/main/res/menu/menu_bottom_nav.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: 🖥feature

#18 [Feature] 맞춤정책 리스트 화면 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/adapter/PolicyListAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/BottomDialogFilterFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/DetailInfoActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/PolicyListActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/viewmodel/PolicyListViewModel.kt
  app/src/main/res/drawable-v24/bg_dwelling_color_radius_4dp.xml
  app/src/main/res/drawable/bg_stroke_gray03_1dp.xml
  app/src/main/res/drawable/bg_white_radius_20dp.xml
  app/src/main/res/drawable/bg_white_radius_top_20dp.xml
  app/src/main/res/drawable/div_policy_list_item.xml
  app/src/main/res/drawable/ic_chevron_down_20.xml
  app/src/main/res/drawable/ic_chevron_left_20.xml
  app/src/main/res/drawable/ic_close_24.xml
  app/src/main/res/drawable/ic_like_24.xml
  app/src/main/res/drawable/ic_like_filled_24.xml
  app/src/main/res/drawable/img_firecracker.9.png
  app/src/main/res/drawable/img_sad.9.png
  app/src/main/res/drawable/selector_like.xml
  app/src/main/res/drawable/selector_rewrite.xml
  app/src/main/res/layout/activity_detail_info.xml
  app/src/main/res/layout/activity_policy_list.xml
  app/src/main/res/layout/dialog_policy_list_rewrite.xml
  app/src/main/res/layout/fragment_bottom_dialog_filter.xml
  app/src/main/res/layout/item_policy_list.xml
  app/src/main/res/values-v23/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: layout, 🖥feature

#21 [Feature] 홈, 정책 리스트 머지 전 발견 못한 버그 해결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/fork/spoonfeed/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/DetailInfoActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/PolicyListActivity.kt
  app/src/main/res/values/themes.xml
Labels: bug

#17 [Feature] 맞춤정책 홈화면, 단계별 필터 화면 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/fork/spoonfeed/domain/model/Age.kt
  app/src/main/java/com/fork/spoonfeed/domain/model/AgeInputType.kt
  app/src/main/java/com/fork/spoonfeed/domain/model/AnnualIncome.kt
  app/src/main/java/com/fork/spoonfeed/domain/model/ChipInputType.kt
  app/src/main/java/com/fork/spoonfeed/domain/model/CompanySize.kt
  app/src/main/java/com/fork/spoonfeed/domain/model/HomeOwnership.kt
  app/src/main/java/com/fork/spoonfeed/domain/model/HouseHolderStatus.kt
  app/src/main/java/com/fork/spoonfeed/domain/model/MedianIncome.kt
  app/src/main/java/com/fork/spoonfeed/domain/model/NetWorth.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/custom/FilterProgress.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policy/view/PolicyFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policy/view/filter/PolicyFilterActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policy/view/filter/PolicyFilterLevelOneFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policy/view/filter/PolicyFilterLevelThreeFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policy/view/filter/PolicyFilterLevelTwoFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policy/view/filter/PolicyFilterViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policy/view/filter/tooltip/MedianIncomeTooltipActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policy/view/filter/tooltip/NetWorthTooltipActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/util/StatusExt.kt
  app/src/main/java/com/fork/spoonfeed/presentation/util/StringExt.kt
  app/src/main/java/com/fork/spoonfeed/presentation/util/ViewExt.kt
  app/src/main/res/color/selector_chip_background_color.xml
  app/src/main/res/color/selector_chip_stroke_tint.xml
  app/src/main/res/color/selector_chip_text_color.xml
  app/src/main/res/drawable/bg_policy_filter_age_input.xml
  app/src/main/res/drawable/bg_policy_filter_level_title.xml
  app/src/main/res/drawable/bg_policy_filter_progress.xml
  app/src/main/res/drawable/bg_policy_filter_save.xml
  app/src/main/res/drawable/ic_check_box.xml
  app/src/main/res/drawable/ic_check_box_filled.xml
  app/src/main/res/drawable/ic_info_policy_filter_resize.xml
  app/src/main/res/drawable/img_policy_sub_title.9.png
  app/src/main/res/layout/activity_median_income_tooltip.xml
  app/src/main/res/layout/activity_net_worth_tooltip.xml
  app/src/main/res/layout/activity_policy_filter.xml
  app/src/main/res/layout/filter_progress.xml
  app/src/main/res/layout/fragment_policy.xml
  app/src/main/res/layout/fragment_policy_filter_level_one.xml
  app/src/main/res/layout/fragment_policy_filter_level_three.xml
  app/src/main/res/layout/fragment_policy_filter_level_two.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values-v23/themes.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: layout, 🖥feature

#23 [Layout] 온보딩 레이아웃 구성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/fork/spoonfeed/presentation/SplashActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/signup/SignupActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/signup/SignupFinishFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/signup/SignupNameFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/signup/SignupTermsConditionFragment.kt
  app/src/main/res/color/selector_check_round_background_color.xml
  app/src/main/res/drawable/ic_kakao.xml
  app/src/main/res/drawable/ic_naver.xml
  app/src/main/res/drawable/img_signup_finish.9.png
  app/src/main/res/drawable/selector_check_round.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_signup_finish.xml
  app/src/main/res/layout/fragment_signup_name.xml
  app/src/main/res/layout/fragment_signup_terms_condition.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: layout

#24 [Feature] 상세페이지 화면 구현 및 홈, 맞춤정책리스트 변경사항 반영
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/fork/spoonfeed/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/ApplyExplainActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/ApplyQualificationActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/BottomDialogFilterFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/DetailInfoActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/PolicyListActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/viewmodel/DetailInfoViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/viewmodel/PolicyListViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/util/DialogUtil.kt
  app/src/main/res/drawable/bg_dwelling_blue_radius_4dp.xml
  app/src/main/res/drawable/bg_finance_purple_radius_4dp.xml
  app/src/main/res/drawable/bg_gray02_stroke_circle.xml
  app/src/main/res/drawable/bg_primary_blue_radius_14dp.xml
  app/src/main/res/drawable/bg_white_radius_8dp.xml
  app/src/main/res/drawable/div_detail_info_gray01_16dp.xml
  app/src/main/res/drawable/div_detail_info_gray06_1dp.xml
  app/src/main/res/drawable/div_policy_list_item_gray02_1dp.xml
  app/src/main/res/drawable/ic_chevron_left_detail_info.xml
  app/src/main/res/drawable/img_curious.9.png
  app/src/main/res/drawable/selector_like.xml
  app/src/main/res/drawable/selector_like_24.xml
  app/src/main/res/layout/activity_apply_explain.xml
  app/src/main/res/layout/activity_apply_qualification.xml
  app/src/main/res/layout/activity_detail_info.xml
  app/src/main/res/layout/activity_policy_list.xml
  app/src/main/res/layout/dialog_policy_list_rewrite.xml
  app/src/main/res/layout/dialog_policy_list_search_done.xml
  app/src/main/res/layout/fragment_bottom_dialog_filter.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_policy_list.xml
  app/src/main/res/values/strings.xml
Labels: layout, 🖥feature

#30 [Layout] 커뮤니티 글 작성 및 상세 레이아웃
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/view/CommunityFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/adapter/CommentAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/CommunityPostActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/CommunityPostCreateActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/ItemDecoration.kt
  app/src/main/res/drawable/bg_community_post_comment.xml
  app/src/main/res/drawable/bg_community_post_create_input.xml
  app/src/main/res/drawable/bg_community_post_detail_divider.xml
  app/src/main/res/drawable/ic_chevron_up_20.xml
  app/src/main/res/drawable/ic_comment_filled_24.xml
  app/src/main/res/drawable/ic_send_comment.xml
  app/src/main/res/layout/activity_community_post.xml
  app/src/main/res/layout/activity_community_post_create.xml
  app/src/main/res/layout/item_community_post_comment.xml
  app/src/main/res/menu/menu_community_post_create_category.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: layout

#32 [Layout] 마이페이지 레이아웃
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: layout

#33 [Layout] 로그아웃, 댓글 수정 다이어로그 띄우기
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/view/CommunityFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/CommunityPostActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/res/drawable/img_comment_bg.9.png
  app/src/main/res/layout/dialog_comment.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: layout

#34 [Layout] 커뮤니티 글작성 상세정보 수정 화면
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/CommunityPostCreateActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/CommunityPostInfoUpdateActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/util/ViewExt.kt
  app/src/main/res/color/selector_chip_stroke_tint_disabled.xml
  app/src/main/res/color/selector_chip_text_color_disabled.xml
  app/src/main/res/drawable/bg_category.xml
  app/src/main/res/layout/activity_community_post.xml
  app/src/main/res/layout/activity_community_post_create.xml
  app/src/main/res/layout/activity_community_post_info_update.xml
  app/src/main/res/layout/item_category_popup.xml
  app/src/main/res/values/array.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: layout

#35 [Layout] 마이페이지 내 정보 페이지 레이아웃
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/MyPageMyInfoActivity.kt
  app/src/main/res/layout/activity_my_page_my_info.xml
  app/src/main/res/values/strings.xml
Labels: layout

#37 [Layout] 맞춤정책 리스트 분기처리 및 마이페이지 내글관리 다이어로그 구현
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/adapter/PostAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/view/SearchInputResultFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/viewmodel/CommunityViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/CommunityPostActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/adapter/MyCommentAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/MyPostManagementPostFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policy/view/filter/PolicyFilterLevelThreeFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/BottomDialogFilterFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/PolicyListActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/viewmodel/PolicyListViewModel.kt
  app/src/main/res/drawable/ic_rearrow.xml
  app/src/main/res/layout/activity_policy_list.xml
  app/src/main/res/layout/fragment_my_post_management.xml
  app/src/main/res/layout/item_comment.xml
  app/src/main/res/layout/item_post.xml
Labels: layout, 🖥feature

#39 [FEAT] 홈뷰 맞춤정책, 상세페이지 연결
  app/src/main/java/com/fork/spoonfeed/presentation/MainActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/home/view/HomeFragment.kt
Labels: 🖥feature

#41 [Feature] 화면 플로우 연결
  app/src/main/java/com/fork/spoonfeed/presentation/MainActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/SplashActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/signup/SignupActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/signup/SignupFinishFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/signup/SignupNameFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/signup/SignupTermsConditionFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policy/view/filter/PolicyFilterActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policy/view/filter/PolicyFilterLevelThreeFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/PolicyListActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/util/ViewExt.kt
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_signup_name.xml
  app/src/main/res/layout/fragment_signup_terms_condition.xml
Labels: 🖥feature

#43 [Setting] 앱 아이콘 적용
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_spoonfeed.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: 🖥feature

#45 [Feature] 정책 리스트 API 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/fork/spoonfeed/data/remote/api/policy/PolicyService.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/PolicyDataSource.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/PolicyDataSourceImpl.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/policy/ResponsePolicyAllData.kt
  app/src/main/java/com/fork/spoonfeed/data/repository/PolicyRepositoryImpl.kt
  app/src/main/java/com/fork/spoonfeed/domain/repository/PolicyRepository.kt
  app/src/main/java/com/fork/spoonfeed/presentation/di/ApiModule.kt
  app/src/main/java/com/fork/spoonfeed/presentation/di/DataSourceModule.kt
  app/src/main/java/com/fork/spoonfeed/presentation/di/RepositoryModule.kt
  app/src/main/java/com/fork/spoonfeed/presentation/di/RetrofitModule.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/view/CommunityFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/viewmodel/CommunityViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/InterastedPolicyActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/NoticeActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/adapter/PolicyListAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/BottomDialogFilterFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/PolicyListActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/viewmodel/PolicyListViewModel.kt
  app/src/main/res/layout/fragment_bottom_dialog_filter.xml
  app/src/main/res/layout/item_policy_list.xml
Labels: 🖥feature

#49 [Feature] 네이버 로그인 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/fork/spoonfeed/data/UserData.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/api/auth/AuthService.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/AuthDataSource.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/AuthDataSourceImpl.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/auth/ResponseLoginWithNaverData.kt
  app/src/main/java/com/fork/spoonfeed/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/fork/spoonfeed/domain/repository/AuthRepository.kt
  app/src/main/java/com/fork/spoonfeed/presentation/SplashActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/di/ApiModule.kt
  app/src/main/java/com/fork/spoonfeed/presentation/di/DataSourceModule.kt
  app/src/main/java/com/fork/spoonfeed/presentation/di/RepositoryModule.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/view/OnboardingActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/view/signup/SignupActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/view/signup/SignupFinishFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/view/signup/SignupNameFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/view/signup/SignupTermsConditionFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/viewmodel/LoginViewModel.kt
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/fragment_signup_finish.xml
  app/src/main/res/layout/fragment_signup_name.xml
  app/src/main/res/layout/fragment_signup_terms_condition.xml
Labels: 🖥feature

#53 [Feature] 카카오 로그인 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/fork/spoonfeed/SpoonFeedApplication.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/api/auth/AuthService.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/AuthDataSource.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/AuthDataSourceImpl.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/auth/ResponseLoginWithKakaoData.kt
  app/src/main/java/com/fork/spoonfeed/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/fork/spoonfeed/domain/repository/AuthRepository.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/view/OnboardingActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/viewmodel/LoginViewModel.kt
  build.gradle
  settings.gradle
Labels: 🖥feature

#55 [Feature] 상세 페이지 서버 API 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/fork/spoonfeed/data/UserData.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/api/policy/PolicyService.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/PolicyDataSource.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/PolicyDataSourceImpl.kt
  app/src/main/java/com/fork/spoonfeed/data/repository/PolicyRepositoryImpl.kt
  app/src/main/java/com/fork/spoonfeed/domain/repository/PolicyRepository.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/viewmodel/LoginViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/DetailInfoActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/PolicyListActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/viewmodel/DetailInfoViewModel.kt
  app/src/main/res/drawable-v24/kakao_login_medium_narrow.9.png
  app/src/main/res/layout/activity_detail_info.xml
  app/src/main/res/layout/activity_kakao_log_in.xml
  app/src/main/res/layout/item_policy_list.xml
  app/src/main/res/values/strings.xml
Labels: 🖥feature

#57 [Feature] 유저 맞춤 정책 API 연결
  app/src/main/java/com/fork/spoonfeed/data/UserData.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/api/auth/AuthService.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/api/policy/PolicyService.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/AuthDataSource.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/AuthDataSourceImpl.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/PolicyDataSource.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/PolicyDataSourceImpl.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/policy/RequestFilteredPolicy.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/policy/ResponseFilteredPolicy.kt
  app/src/main/java/com/fork/spoonfeed/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/fork/spoonfeed/data/repository/PolicyRepositoryImpl.kt
  app/src/main/java/com/fork/spoonfeed/domain/model/Age.kt
  app/src/main/java/com/fork/spoonfeed/domain/model/AnnualIncome.kt
  app/src/main/java/com/fork/spoonfeed/domain/model/CompanySize.kt
  app/src/main/java/com/fork/spoonfeed/domain/model/HomeOwnership.kt
  app/src/main/java/com/fork/spoonfeed/domain/model/HouseHolderStatus.kt
  app/src/main/java/com/fork/spoonfeed/domain/model/MedianIncome.kt
  app/src/main/java/com/fork/spoonfeed/domain/model/NetWorth.kt
  app/src/main/java/com/fork/spoonfeed/domain/repository/AuthRepository.kt
  app/src/main/java/com/fork/spoonfeed/domain/repository/PolicyRepository.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/viewmodel/LoginViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policy/view/filter/PolicyFilterActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policy/view/filter/PolicyFilterLevelThreeFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policy/view/filter/PolicyFilterViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/PolicyListActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/viewmodel/DetailInfoViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/viewmodel/PolicyListViewModel.kt
Labels: 🖥feature

#59 [Feature] 온보딩 API 연결
  app/src/main/java/com/fork/spoonfeed/data/remote/api/user/UserService.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/UserDataSource.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/UserDataSourceImpl.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/user/RequestUserNickNameData.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/user/ResponseUserNickNameData.kt
  app/src/main/java/com/fork/spoonfeed/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/fork/spoonfeed/domain/repository/UserRepository.kt
  app/src/main/java/com/fork/spoonfeed/presentation/di/ApiModule.kt
  app/src/main/java/com/fork/spoonfeed/presentation/di/DataSourceModule.kt
  app/src/main/java/com/fork/spoonfeed/presentation/di/RepositoryModule.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/view/OnboardingActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/view/signup/SignupActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/view/signup/SignupFinishFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/view/signup/SignupNameFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/view/signup/SignupTermsConditionFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/viewmodel/LoginViewModel.kt
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/fragment_signup_name.xml
  app/src/main/res/layout/fragment_signup_terms_condition.xml
Labels: 🖥feature

#63 [Feature] 커뮤니티 글 작성 서버 연결
  app/src/main/java/com/fork/spoonfeed/data/remote/api/community/PostService.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/api/user/UserService.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/PostDataSource.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/PostDataSourceImpl.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/UserDataSource.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/UserDataSourceImpl.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/community/RequestSendPostData.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/community/ResponseSendPostData.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/user/ResponseUserData.kt
  app/src/main/java/com/fork/spoonfeed/data/repository/PostRepositoryImpl.kt
  app/src/main/java/com/fork/spoonfeed/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/fork/spoonfeed/domain/repository/PostRepository.kt
  app/src/main/java/com/fork/spoonfeed/domain/repository/UserRepository.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/view/CommunityFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/CommunityPostCreateActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/CommunityPostInfoUpdateActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/viewmodel/CommunityPostCreateViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/viewmodel/CommunityPostInfoUpdateViewModel.kt
  app/src/main/res/layout/activity_community_post_info_update.xml
Labels: 🖥feature

#66 [Hotfix] 글 작성후 커뮤니티 화면에서 바로 글이 불러와지지 않는 문제 해결
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/CommunityPostCreateActivity.kt
Labels: hotfix
