Repository dnd-side-project/dnd-6th-5-android, pull requests merged in 2022-04, with the labels that each got.

#111 [FIX] #110 - CI관련 에러 해결
  app/build.gradle
  app/src/main/AndroidManifest.xml
Labels: bug

#113 [Feature] 유저관련 변경된 api DTO 추가 및 신고사유선택 로직 변경
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/fork/spoonfeed/data/remote/api/community/PostService.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/api/user/UserService.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/PostDataSource.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/UserDataSource.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/UserDataSourceImpl.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/community/ResponsePostAllData.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/user/ResponseBlockUserData.kt
  app/src/main/java/com/fork/spoonfeed/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/fork/spoonfeed/domain/repository/UserRepository.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/temp.java
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/viewmodel/CommunityViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/viewmodel/SearchViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/UserReportReasonActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/viewmodel/CommunityPostViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/view/OnboardingActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/util/ViewExt.kt
  app/src/main/res/drawable/ic_selector_user_report.xml
  app/src/main/res/layout/activity_user_report_reason.xml
Labels: 🖥feature

#114 [FEATURE] 자동 로그인 구현
  app/src/main/java/com/fork/spoonfeed/data/local/AutoLoginManager.kt
  app/src/main/java/com/fork/spoonfeed/data/local/AutoLoginPlatformManager.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/api/auth/AuthService.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/AuthDataSource.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/AuthDataSourceImpl.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/auth/ResponseLogoutWithNaverData.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/auth/ResponseTokenData.kt
  app/src/main/java/com/fork/spoonfeed/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/fork/spoonfeed/domain/repository/AuthRepository.kt
  app/src/main/java/com/fork/spoonfeed/presentation/di/DataSourceModule.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/temp.java
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/view/OnboardingActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/viewmodel/LoginViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/splash/view/SplashActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/splash/viewmodel/SplashViewModel.kt
Labels: 🖥feature

#117 [Feature] 바텀시트 Bundle로 변경 및 좋아요 관련 버그 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/fork/spoonfeed/data/remote/api/community/PostService.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/PostDataSourceImpl.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/user/ResponseUserLikePolicyData.kt
  app/src/main/java/com/fork/spoonfeed/domain/model/CommentData.kt
  app/src/main/java/com/fork/spoonfeed/presentation/MainActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/di/RetrofitModule.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/adapter/PostAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/viewmodel/SearchViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/adapter/CommentAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/CommunityPostActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/home/adapter/MyLikePolicyHomeAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/adapter/MyCommentAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/adapter/MyPostAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/BottomDialogMyPageFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/DetailInfoActivity.kt
  app/src/main/res/layout/item_interasted_policy.xml
Labels: bug, 🖥feature

#118 [FEATURE] 댓글 신고 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/fork/spoonfeed/data/local/dao/CommentReportDao.kt
  app/src/main/java/com/fork/spoonfeed/data/local/database/AppDatabase.kt
  app/src/main/java/com/fork/spoonfeed/data/local/entity/CommentReportData.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/api/community/CommentService.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/CommentDataSource.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/CommentDataSourceImpl.kt
  app/src/main/java/com/fork/spoonfeed/data/repository/CommentRepositoryImpl.kt
  app/src/main/java/com/fork/spoonfeed/domain/repository/CommentRepository.kt
  app/src/main/java/com/fork/spoonfeed/presentation/di/DatabaseModule.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/adapter/CommentAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/BottomDialogReport.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/CommunityPostActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/UserReportReasonActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/viewmodel/CommunityPostViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/viewmodel/ReportViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/SecessionActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/util/ViewExt.kt
  app/src/main/res/layout/activity_user_report_reason.xml
Labels: 🖥feature

#119 [Feature] 유저 차단 기능 구현
  app/src/main/java/com/fork/spoonfeed/data/remote/model/community/ResponsePostData.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/BottomDialogReport.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/CommunityPostActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/viewmodel/CommunityPostViewModel.kt
  app/src/main/res/layout/dialog_user_report.xml
  app/src/main/res/layout/fragment_bottom_dialog_report_user.xml
Labels: 🖥feature

#121 [HOTFIX] 커뮤니티 관련 수정사항 반영
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/adapter/PostAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/BottomDialogReport.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/CommunityPostCreateActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/CommunityPostInfoUpdateActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/adapter/PolicyListAdapter.kt
Labels: bug

#123 [FEATURE] 마이페이지 닉네임 중복 에러 해결 및 사용자 이메일 저장
  app/src/main/java/com/fork/spoonfeed/data/UserData.kt
  app/src/main/java/com/fork/spoonfeed/data/local/AutoLoginManager.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/MyPageMyInfoActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/viewmodel/MyPageMyInfoViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/view/OnboardingActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/viewmodel/LoginViewModel.kt
  app/src/main/res/layout/activity_interasted_policy.xml
  app/src/main/res/layout/activity_my_page_my_info.xml
  app/src/main/res/layout/fragment_search_input_result.xml
Labels: bug, layout, 🖥feature

#126 [HOTFIX] 유저 차단 텍스트를 유저 신고로 변경
  app/build.gradle
  app/src/main/res/layout/dialog_user_report.xml
  app/src/main/res/layout/fragment_bottom_dialog_report_user.xml
Labels: hotfix
