Repository dnd-side-project/dnd-6th-5-android, pull requests merged in 2022-03, with the labels that each got.

#68 [Feature] 마이페이지 내정보 수정, 로그아웃&탈퇴시 로그인화면으로 이동
  app/src/main/java/com/fork/spoonfeed/data/remote/api/user/UserService.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/UserDataSource.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/UserDataSourceImpl.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/user/RequestPatchUserFilterData.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/user/ResponsePatchUserFilterData.kt
  app/src/main/java/com/fork/spoonfeed/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/fork/spoonfeed/domain/repository/UserRepository.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/MyPageMyInfoActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/SecessionActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/viewmodel/MyPageMyInfoViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/util/StatusExt.kt
  app/src/main/java/com/fork/spoonfeed/presentation/util/ViewExt.kt
  app/src/main/res/layout/activity_my_page_my_info.xml
Labels: 🖥feature

#69 [FEAT] 정책 좋아요 버튼 기능 구현 및 카운트 표시
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/adapter/PolicyListAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/PolicyListActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/viewmodel/PolicyListViewModel.kt
Labels: 🖥feature

#70 [FEAT] 맞춤정책 정보 저장안하고 필터링하는 기능 API 연결
  app/src/main/java/com/fork/spoonfeed/data/remote/api/policy/PolicyService.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/PolicyDataSourceImpl.kt
Labels: 🖥feature

#71 [FEAT] 커뮤니티 글/댓글 수정/삭제, 검색, 작성자와 일반 유저 분기처리 구현
  app/src/main/java/com/fork/spoonfeed/data/remote/api/community/CommentService.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/api/community/PostService.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/CommentDataSource.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/CommentDataSourceImpl.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/PostDataSource.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/PostDataSourceImpl.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/community/RequestPatchCommentData.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/community/ResponsePatchCommentData.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/community/ResponseSearchPostAllData.kt
  app/src/main/java/com/fork/spoonfeed/data/repository/CommentRepositoryImpl.kt
  app/src/main/java/com/fork/spoonfeed/data/repository/PostRepositoryImpl.kt
  app/src/main/java/com/fork/spoonfeed/domain/repository/CommentRepository.kt
  app/src/main/java/com/fork/spoonfeed/domain/repository/PostRepository.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/view/SearchInputActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/view/SearchInputResultFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/viewmodel/SearchViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/adapter/CommentAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/CommunityPostActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/CommunityPostCreateActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/viewmodel/CommunityPostViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/MyPostManagementCommentFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/util/ViewExt.kt
  app/src/main/res/layout/activity_search_input.xml
  app/src/main/res/layout/fragment_search_input_result.xml
Labels: 🖥feature

#73 [Feature] 홈화면 관심있는 정책 3개 보이기
  app/src/main/java/com/fork/spoonfeed/data/remote/model/user/ResponseUserLikePolicyData.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/home/adapter/MyLikePolicyHomeAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/adapter/MyLikePolicyAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/MyLikePolicyActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/adapter/PolicyListAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/ApplyExplainActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/ApplyQualificationActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/DetailInfoActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/PolicyListActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/viewmodel/DetailInfoViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/util/LinearLayoutManagerWrapper.kt
  app/src/main/res/layout/activity_apply_explain.xml
  app/src/main/res/layout/activity_apply_qualification.xml
  app/src/main/res/layout/activity_interasted_policy.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_post_management.xml
  app/src/main/res/layout/fragment_my_post_management_comment.xml
  app/src/main/res/layout/item_interasted_policy.xml
Labels: 🖥feature

#74 [Feature] 마이페이지 탈퇴하기 api 연결 및 노션링크 연결
  app/src/main/java/com/fork/spoonfeed/data/remote/api/auth/AuthService.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/api/user/UserService.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/AuthDataSource.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/AuthDataSourceImpl.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/auth/ResponseDeleteWithKakaoData.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/auth/ResponseDeleteWithNaverData.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/user/ResponseUserLikePolicyData.kt
  app/src/main/java/com/fork/spoonfeed/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/fork/spoonfeed/domain/repository/AuthRepository.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/home/adapter/MyLikePolicyHomeAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/MyLikePolicyActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/SecessionActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/res/layout/item_interasted_policy.xml
Labels: 🖥feature

#76 [Hotfix] 정책 상세의 좋아요 버튼 구현 및 상세페이지, 홈화면 text겹치는 부분 수정
  app/src/main/java/com/fork/spoonfeed/domain/model/LikeBtnState.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/home/adapter/MyLikePolicyHomeAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/adapter/PolicyListAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/DetailInfoActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/PolicyListActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/viewmodel/DetailInfoViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/viewmodel/PolicyListViewModel.kt
  app/src/main/res/layout/activity_detail_info.xml
Labels: hotfix, 🖥feature

#86 [Hotfix] 정책 상세 좋아요, 커뮤니티 수정/삭제 메뉴
  app/src/main/java/com/fork/spoonfeed/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/adapter/CommentAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/CommunityPostActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/adapter/MyCommentAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/adapter/MyPostAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/BottomDialogMyPageFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/MyPostManagementCommentFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/MyPostManagementPostFragment.kt
  app/src/main/res/layout/fragment_bottom_dialog_my_page.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: hotfix, 🖥feature

#77 [FEATURE] 네이버 자동로그인, 온보딩 넘기기, 중복닉네임 처리 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/fork/spoonfeed/data/local/AutoLoginPlatformManager.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/api/user/UserService.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/AuthDataSource.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/AuthDataSourceImpl.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/UserDataSource.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/datasource/UserDataSourceImpl.kt
  app/src/main/java/com/fork/spoonfeed/data/remote/model/user/ResponseUserNameDuplicate.kt
  app/src/main/java/com/fork/spoonfeed/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/fork/spoonfeed/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/fork/spoonfeed/domain/repository/AuthRepository.kt
  app/src/main/java/com/fork/spoonfeed/domain/repository/UserRepository.kt
  app/src/main/java/com/fork/spoonfeed/presentation/SplashActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/di/DataSourceModule.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/view/OnboardingActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/view/signup/SignupNameFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/viewmodel/LoginViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/splash/view/SplashActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/splash/viewmodel/SplashViewModel.kt
  app/src/main/res/layout/activity_splash.xml
Labels: 🖥feature

#87 [Hotfix] 닉네임 수정이나 이용약관 동의를 하지 않아도 자동로그인이 되는 문제 해결
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/view/signup/SignupFinishFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/view/signup/SignupNameFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/viewmodel/LoginViewModel.kt
Labels: hotfix

#88 [Layout] 정책 상세페이지 레이아웃 수정
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/DetailInfoActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/viewmodel/DetailInfoViewModel.kt
  app/src/main/res/layout/activity_detail_info.xml
Labels: layout

#90 [Feature] 마이페이지 체크박스 삭제 및 닉네임 수정시 중복확인 처리
  app/src/main/java/com/fork/spoonfeed/data/remote/model/user/ResponseUserData.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/CommunityPostInfoUpdateActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/viewmodel/CommunityPostCreateViewModel.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/MyPageMyInfoActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/viewmodel/MyPageMyInfoViewModel.kt
  app/src/main/res/layout/activity_my_page_my_info.xml
  app/src/main/res/layout/dialog_goto_policy.xml
  app/src/main/res/values/strings.xml
Labels: 🖥feature

#91 [Feature] 상태바 텍스트 보이게 수정, 화면 회전 고정
  app/src/main/java/com/fork/spoonfeed/presentation/base/BaseViewUtil.kt
  app/src/main/res/values/themes.xml
Labels: layout

#92 [FEAT] - #83 내정보 없을 때 맞춤정책 화면으로 이동 구현
  app/src/main/java/com/fork/spoonfeed/presentation/MainActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/CommunityPostInfoUpdateActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/MyPageMyInfoActivity.kt
Labels: 🖥feature

#93 [Hotfix] 커뮤니티 검색 수정
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/view/SearchInputActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/communitypost/view/CommunityPostCreateActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/util/ViewExt.kt
  app/src/main/res/layout/activity_search_input.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: hotfix, 🖥feature

#94 [Feature] 온보딩 동의항목 링크 연결, 둘러보기 안보이게 수정
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/view/signup/SignupTermsConditionFragment.kt
  app/src/main/res/layout/activity_onboarding.xml
Labels: layout, 🖥feature

#95 [Layout] 온보딩 레이아웃 수정
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/view/signup/SignupActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/view/signup/SignupNameFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/view/signup/SignupTermsConditionFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/util/ViewExt.kt
  app/src/main/res/layout/fragment_signup_name.xml
Labels: hotfix, layout

#97 [Hotfix] 커뮤니티 결과 리스트 및 맞춤정책 에러처리
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/adapter/PostAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/view/CommunityFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/view/SearchInputActivity.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/view/SearchInputResultFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/BottomDialogMyPageFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/viewmodel/PolicyListViewModel.kt
  app/src/main/res/layout/item_post.xml
Labels: hotfix, 🖥feature

#98 [Layout] UI 터치영역 수정
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/view/CommunityFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/res/drawable/ic_mypage_chevron.xml
  app/src/main/res/layout/activity_community_post.xml
  app/src/main/res/layout/activity_interasted_policy.xml
  app/src/main/res/layout/activity_my_post_management.xml
  app/src/main/res/layout/activity_notice.xml
  app/src/main/res/layout/activity_policy_list.xml
  app/src/main/res/layout/activity_question.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_post.xml
Labels: layout

#99 [Hotfix] 커뮤니티 글 작성자 분기처리
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/adapter/PostAdapter.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/view/CommunityFragment.kt
  app/src/main/java/com/fork/spoonfeed/presentation/ui/community/view/SearchInputResultFragment.kt
Labels: hotfix, 🖥feature

#100 [Layout] 레이아웃에 적용된 아이콘 변경
  app/src/main/java/com/fork/spoonfeed/presentation/ui/onboarding/view/signup/SignupActivity.kt
  app/src/main/res/drawable/ic_empty.xml
  app/src/main/res/drawable/ic_find.xml
  app/src/main/res/drawable/ic_find_background.xml
  app/src/main/res/drawable/ic_finish_filter.xml
  app/src/main/res/drawable/ic_info.xml
  app/src/main/res/drawable/ic_info_item.xml
  app/src/main/res/drawable/ic_logo_text.xml
  app/src/main/res/drawable/ic_onboard_background.xml
  app/src/main/res/drawable/ic_onboard_ready.xml
  app/src/main/res/drawable/ic_policy_all.xml
  app/src/main/res/drawable/ic_policy_dwelling.xml
  app/src/main/res/drawable/ic_policy_finance.xml
  app/src/main/res/drawable/ic_splash_background.xml
  app/src/main/res/drawable/img_logo.9.png
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_policy_list.xml
  app/src/main/res/layout/activity_secession.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/dialog_policy_list_search_done.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_policy.xml
  app/src/main/res/layout/fragment_signup_finish.xml
  app/src/main/res/values/strings.xml
Labels: layout

#102 [Fix] 맞춤정책 리스트 데이터 없을때 ui 반영하는 로직 수정
  app/src/main/java/com/fork/spoonfeed/presentation/ui/policylist/view/PolicyListActivity.kt
  app/src/main/res/layout/activity_policy_list.xml
Labels: 🖥feature

#104 [Fix] yml base url 추가
  .github/workflows/android.yml
Labels: hotfix

#105 [Fix] BuildConfig에 base url 추가
  app/build.gradle
  app/src/main/java/com/fork/spoonfeed/presentation/di/RetrofitModule.kt
Labels: hotfix

#107 [Layout] overscroll 색상 변경
  app/src/main/res/values/themes.xml
Labels: layout
